# Generated by Django 3.2.5 on 2021-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(default=1638886387.5337238)),
                ('updated_at', models.TextField(blank=True)),
                ('counted_at', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=62)),
                ('preview_img', models.TextField(blank=True, default='default.png')),
                ('kakao_img', models.URLField()),
                ('title', models.CharField(max_length=124)),
                ('content', models.TextField()),
                ('date', models.TextField()),
                ('ref', models.URLField()),
            ],
            options={
                'ordering': ['-created_at', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Potal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('is_checked', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=True)),
                ('non_press', models.ManyToManyField(blank=True, related_name='non_press', to='news.Press')),
                ('press', models.ManyToManyField(blank=True, related_name='user_press', to='news.Press')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
